name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.8"]
    steps:
    - name: 🛎️ Checkout Code
      uses: actions/checkout@v4

    - name: 📥 Install Dependencies (pyenv, Python)
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev zlib1g-dev \
                            libbz2-dev libreadline-dev libsqlite3-dev curl \
                            libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"
        pyenv install ${{ matrix.python-version }} -s
        pyenv global ${{ matrix.python-version }}

    - name: 💾 Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 🔹 Activate Virtual Environment & Install Dependencies
      run: |
        chmod +x activate
        source activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black

    - name: 🎨 Auto-Format Code with Black
      run: |
        black .

    - name: 🔎 Run Pylint
      run: |
        pylint --ignore=venv,migrations $(git ls-files '*.py')
